//
//  WWContentDefinitions.h
//  APIObjectiveC
//
//  Created by Kevin Liang on 9/17/14.
//  Copyright (c) 2014 Wonder Workshop inc. (https://www.makewonder.com/) All rights reserved.
//

// default eye animations
FOUNDATION_EXPORT NSString *const WW_EYEANIM_FULL_BLINK;
FOUNDATION_EXPORT NSString *const WW_EYEANIM_SWIRL;
FOUNDATION_EXPORT NSString *const WW_EYEANIM_WINK;

// defualt robot sounds"
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_GIGGLE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_AIRPLANE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_OKAY;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_BYE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_SIGH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_BEEP;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_BRAGGING;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_CONFUSED;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_COOL;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_CROCODILE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_HUH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_HI;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_WAH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_WOW;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_DINOSAUR;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_ELEPHANT;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_ENGINE_REV;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_WEE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_WOOHOO;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_GOAT;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_CAT;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_DOG;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_LION;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_GOBBLE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_HAHA;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_OOH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_GRUNT;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_HELICOPTER;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_HORSE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_LASERS;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_SQUEAK;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_SNORING;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_SPEED_BOOST;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_SURPRISED;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_TAH_DAH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_YAWN;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_TIRE_SQUEAL;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_TRAIN;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_HORN;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_TRUMPET;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_BOAT;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_BUZZ;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_WEEHEE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_UH_OH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_SIREN;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_UH_HUH;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_YIPPE;
FOUNDATION_EXPORT NSString *const WW_SOUNDFILE_LETS_GO;

